## Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
#version: '3'
#
##Define services
#services:
#  #PostgreSQL Database for the application
#  postgres:
#    image: my-docker-postgres
#    container_name: scrum-postgres
#    #Volume mounted for database for the storage
#    volumes:
#      - scrum-data:/var/lib/postgresql/data
#    ports:
#      - 5432:5432 # Forward the exposed port 5432 on the container to port 5432 on the host machine
#
#    #Environment variable for DB name, user and password
#    environment:
#      - POSTGRES_DB=event
#      - POSTGRES_USER=scrum
#      - POSTGRES_PASSWORD=scrum
#
#
#  #Back-end Spring Boot Application
#  scrum-app:
#    #The docker file in scrum-app build the jar and provides the docker image with the following name.
#    build: .
#    container_name: scrum-app
#
#    #Environment variables for Spring Boot Application.
#    environment:
#      - DB_SERVER=postgres
#      - POSTGRES_DB=event
#      - POSTGRES_USER=scrum
#      - POSTGRES_PASSWORD=scrum
#    ports:
#      - 8080:8080 # Forward the exposed port 8080 on the container to port 8080 on the host machine
#    links:
#      - postgres
#    restart: on-failure
#
#
#
##Volumes for DB data
#volumes:
#  scrum-data:


version: '3.1'
services:
  app:
    container_name: event-service
    image: springboot-postgresql
    build: .
    ports:
    - "8080:8080"
    depends_on:
      - postgresqldb

  postgresqldb:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
      - POSTGRES_DB=event
